/*
 * Formulario Corto
 * El que contiene todos los controladores del formulario
 */
package com.sv.udb.forms;

import com.sv.udb.clases.Controlador;
import com.sv.udb.clases.Jugadores;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Estudiante
 */
public class Corto extends javax.swing.JFrame {
    Controlador obj;

    /**
     * Creates new form Corto
     */
    public Corto() {
        initComponents();
        obj = new Controlador();
    }
    
    private void llenarLista()
    {
        DefaultListModel<Jugadores> model = new DefaultListModel<>();
        for (Jugadores jugador : obj.listaJugadores()) {
            model.addElement(jugador);
        }
        this.lstJugadores.setModel((DefaultListModel)model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEstatura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstJugadores = new javax.swing.JList<>();
        btnJugadorAlto = new javax.swing.JButton();
        btnMenorEdad = new javax.swing.JButton();
        btnPesaMas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmbEquipo1 = new javax.swing.JComboBox<>();
        cmbEquipo2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listEquipo1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listEquipo2 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreEquipo = new javax.swing.JTextField();
        btnAgregarEquipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingrese los datos para un jugador:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 104, -1));

        jLabel3.setText("Edad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        getContentPane().add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 104, -1));

        jLabel4.setText("Estatura:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        getContentPane().add(txtEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 104, -1));

        jLabel5.setText("Peso:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));
        getContentPane().add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 104, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        jLabel6.setText("Lista de jugadores:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jScrollPane1.setViewportView(lstJugadores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 149, 146));

        btnJugadorAlto.setText("El jugador más alto");
        btnJugadorAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugadorAltoActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugadorAlto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        btnMenorEdad.setText("El jugador menor edad");
        btnMenorEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenorEdadActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenorEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        btnPesaMas.setText("El jugador que más pesa");
        btnPesaMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesaMasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesaMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipos"));

        jScrollPane2.setViewportView(listEquipo1);

        jScrollPane3.setViewportView(listEquipo2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cmbEquipo1, 0, 130, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cmbEquipo2, 0, 124, Short.MAX_VALUE))
                .addGap(122, 122, 122))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbEquipo1)
                    .addComponent(cmbEquipo2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 300, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Equipo"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Nombre de equipo:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 36, -1, -1));
        jPanel2.add(txtNombreEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 33, 150, -1));

        btnAgregarEquipo.setText("Agregar");
        jPanel2.add(btnAgregarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 71, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 11, 340, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Evento del boton agregar, que ejecuta el metodo agregarJugador
     * @param evt 
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try
        {
            String nombre = txtNombre.getText();
            int edad = Integer.parseInt(txtEdad.getText());
            int estatura = Integer.parseInt(txtEstatura.getText());
            double peso = Double.parseDouble(txtPeso.getText());
            obj.agregarJugador(nombre, edad, estatura, peso);
            JOptionPane.showMessageDialog(this, "Ha ingresao un jugador", "Guardado", JOptionPane.INFORMATION_MESSAGE);
            this.llenarLista();
            txtNombre.setText("");
            txtEdad.setText("");
            txtEstatura.setText("");
            txtPeso.setText("");
        }
        catch(Exception e)
        {
            System.err.println("Error " + e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnJugadorAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugadorAltoActionPerformed
        obj.jugadorMasAlto();
    }//GEN-LAST:event_btnJugadorAltoActionPerformed

    private void btnMenorEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenorEdadActionPerformed
        obj.jugadorMenorEdad();
    }//GEN-LAST:event_btnMenorEdadActionPerformed

    private void btnPesaMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesaMasActionPerformed
        obj.jugadorMasPeso();
    }//GEN-LAST:event_btnPesaMasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Corto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Corto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Corto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Corto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Corto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarEquipo;
    private javax.swing.JButton btnJugadorAlto;
    private javax.swing.JButton btnMenorEdad;
    private javax.swing.JButton btnPesaMas;
    private javax.swing.JComboBox<String> cmbEquipo1;
    private javax.swing.JComboBox<String> cmbEquipo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listEquipo1;
    private javax.swing.JList<String> listEquipo2;
    private javax.swing.JList<String> lstJugadores;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEstatura;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEquipo;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
